services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    container_name: redis

  web:
    env_file:
      - .env
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    
  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    container_name: postgresdb

  celery:
    env_file:
      - .env
    build: .
    command: celery -A petroleum_prices worker --beat --scheduler django --loglevel=info
    volumes:
      - .:/app
