services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

  web:
    env_file:
      - .env
    restart: always
    build: .
    command: gunicorn petroleum_prices.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - postgresdb
    
  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  worker:
    env_file:
      - .env
    build: .
    command: celery -A petroleum_prices worker --beat --scheduler django --loglevel=info
    
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/static
      - media_volume:/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
