services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

  web:
    env_file:
      - .env
    build: .
    command: sh -c 'python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py collectstatic &&
                gunicorn petroleum_prices.wsgi:application --bind 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - static_volume:/static
      - media_volume:/media
    
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  worker:
    env_file:
      - .env
    build: .
    command: celery -A petroleum_prices worker --beat --scheduler django --loglevel=info

volumes:
  static_volume:
  media_volume:
