# Generated by Django 4.2.9 on 2024-01-24 14:31

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetroleumCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('petroleum_code', models.CharField(max_length=4)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PetroleumMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sort', models.CharField(choices=[('AI100', 'Ai100'), ('AI98', 'Ai98'), ('AI95', 'Ai95'), ('AI92', 'Ai92'), ('DTL', 'Dtl'), ('DTD', 'Dtd'), ('DTZ', 'Dtz'), ('Other products', 'Other Products')], max_length=20)),
                ('petroleum_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.petroleumcode')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
