# Generated by Django 4.2.9 on 2024-01-25 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petroleummap',
            name='petroleum_code',
        ),
        migrations.AddField(
            model_name='petroleumcode',
            name='sort',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='rest_api.petroleummap'),
            preserve_default=False,
        ),
    ]
