services:
  redis:
    image: "redis"
    restart: unless-stopped

  web:
    env_file:
      - .env
    restart: unless-stopped
    image: ghcr.io/edwa1401/petroleum-prices:main
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic &&
                    gunicorn petroleum_prices.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:./static
      - media_volume:./media
    depends_on:
      postgresdb:
        condition: service_healthy
    
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  worker:
    env_file:
      - .env
    restart: unless-stopped
    image: ghcr.io/edwa1401/petroleum-prices:main
    command: celery -A petroleum_prices worker --beat --scheduler django --loglevel=info

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - static_volume:./static
      - media_volume:./media
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro

    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  postgres-data:
