services:
  redis:
    image: "redis"

  web:
    env_file:
      - .env
    restart: always
    image: ghcr.io/edwa1401/petroleum-prices:main
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn petroleum_prices.wsgi:application --bind 0.0.0.0:8000
                    "
    expose:
      - 8000
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - postgresdb
    
  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  worker:
    env_file:
      - .env
    image: ghcr.io/edwa1401/petroleum-prices:main
    command: celery -A petroleum_prices worker --beat --scheduler django --loglevel=info

  nginx:
    image: nginx
    volumes:
      - static_volume:/static
      - media_volume:/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./petroleum-prices.crt:/nginx/ssl/petroleum-prices.crt:ro
      - ./petroleum-prices.key:/nginx/ssl/petroleum-prices.key:ro
      - ./ca.crt:/nginx/ssl/ca.crt:ro

    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
