services:
  redis:
    image: "redis"

  web:
    env_file:
      - .env
    restart: always
    image: ghcr.io/edwa1401/petroleum-prices:main
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
    
  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  worker:
    env_file:
      - .env
    image: ghcr.io/edwa1401/petroleum-prices:main
    command: celery -A petroleum_prices worker --beat --scheduler django --loglevel=info
