# Generated by Django 4.2.9 on 2024-01-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallo',
            name='msg',
            field=models.TextField(default='hello'),
        ),
    ]
