# Generated by Django 4.2.9 on 2024-01-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_hallo_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallo',
            name='msg',
            field=models.TextField(default='hallo'),
        ),
    ]
