# Generated by Django 4.2.6 on 2023-10-30 19:37

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('day', models.DateField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=1000)),
                ('metric', models.CharField(max_length=20)),
                ('trade_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='spimex_parser.tradeday')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=1000)),
                ('base', models.CharField(max_length=1000)),
                ('volume', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('price_change_amount', models.CharField(max_length=20)),
                ('price_change_ratio', models.CharField(max_length=20)),
                ('price_min', models.CharField(max_length=20)),
                ('price_avg', models.CharField(max_length=20)),
                ('price_max', models.CharField(max_length=20)),
                ('price_market', models.CharField(max_length=20)),
                ('price_best_bid', models.CharField(max_length=20)),
                ('price_best_call', models.CharField(max_length=20)),
                ('num_lots', models.CharField(max_length=10)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='spimex_parser.section')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
