# Generated by Django 4.2.6 on 2023-10-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spimex_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='num_of_lots',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
