# Generated by Django 4.2.6 on 2023-10-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spimex_parser', '0002_contract_num_of_lots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='num_lots',
        ),
        migrations.AlterField(
            model_name='contract',
            name='num_of_lots',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price_avg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price_best_bid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price_best_call',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price_change_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price_change_ratio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price_market',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price_max',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price_min',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
