# Generated by Django 4.2.6 on 2023-11-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petroleum',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='petroleum',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='petroleum',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='petroleum',
            name='volume',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
