# Generated by Django 4.2.6 on 2023-11-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices_analyzer', '0002_alter_petroleum_amount_alter_petroleum_density_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petroleum',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='petroleum',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
