# Generated by Django 4.2.6 on 2023-11-09 09:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prices_analyzer', '0003_petroleum_retail_price_alter_petroleum_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(max_length=4)),
                ('basis_name', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('product_key', models.CharField(max_length=4)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sort', models.CharField(max_length=20)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='petroleum',
            options={'get_latest_by': 'day', 'ordering': ['-day']},
        ),
        migrations.RemoveField(
            model_name='petroleum',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='petroleum',
            name='base',
        ),
        migrations.RemoveField(
            model_name='petroleum',
            name='base_name',
        ),
        migrations.RemoveField(
            model_name='petroleum',
            name='retail_price',
        ),
        migrations.AlterField(
            model_name='petroleum',
            name='density',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.75'), 'Ab'), (Decimal('0.83999999999999996891375531049561686813831329345703125'), 'Dt'), (Decimal('0'), 'Other Products')], decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='petroleum',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='petroleum',
            name='basis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='petroleums', to='prices_analyzer.basis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='petroleum',
            name='product_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petroleums', to='prices_analyzer.productkey'),
        ),
        migrations.AlterField(
            model_name='petroleum',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petroleums', to='prices_analyzer.sort'),
        ),
    ]
