# Generated by Django 4.2.6 on 2023-11-09 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rail_tariff', '0003_remove_productionplace_basis_delete_depot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prices_analyzer', '0004_basis_productkey_sort_alter_petroleum_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='prices_analyzer.depot')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rzd_code', models.SmallIntegerField()),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='basis',
            old_name='basis_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productkey',
            old_name='product_key',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='petroleum',
            name='sort',
        ),
        migrations.AddField(
            model_name='productkey',
            name='sort',
            field=models.CharField(choices=[('AI100', 'Ai100'), ('AI98', 'Ai98'), ('AI95', 'Ai95'), ('AI92', 'Ai92'), ('DTL', 'Dtl'), ('DTD', 'Dtd'), ('DTZ', 'Dtz'), ('Other products', 'Other Products')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sort',
        ),
        migrations.AddField(
            model_name='productionplace',
            name='basis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prices_analyzer.basis'),
        ),
        migrations.AddField(
            model_name='prices',
            name='petroleum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='prices_analyzer.petroleum'),
        ),
        migrations.AddField(
            model_name='prices',
            name='production_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='prices_analyzer.productionplace'),
        ),
        migrations.AddField(
            model_name='prices',
            name='rail_tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='rail_tariff.railtariff'),
        ),
        migrations.AddField(
            model_name='depot',
            name='basis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='prices_analyzer.basis'),
        ),
        migrations.AddField(
            model_name='depot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to=settings.AUTH_USER_MODEL),
        ),
    ]
