# Generated by Django 4.2.6 on 2023-11-10 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rail_tariff', '0004_rzdcode_alter_railtariff_rail_code_base_from_and_more'),
        ('prices_analyzer', '0005_depot_prices_productionplace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depot',
            name='basis',
        ),
        migrations.AddField(
            model_name='depot',
            name='rzd_code',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='rail_tariff.rzdcode'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='depot',
            name='user',
        ),
        migrations.AlterField(
            model_name='productionplace',
            name='basis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='prices_analyzer.basis'),
        ),
        migrations.AlterField(
            model_name='productionplace',
            name='rzd_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='rail_tariff.rzdcode'),
        ),
        migrations.AddField(
            model_name='depot',
            name='user',
            field=models.ManyToManyField(related_name='depots', to=settings.AUTH_USER_MODEL),
        ),
    ]
