# Generated by Django 4.2.6 on 2023-11-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices_analyzer', '0006_remove_depot_basis_depot_rzd_code_remove_depot_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petroleum',
            options={'get_latest_by': 'day', 'ordering': ['-day', 'price']},
        ),
    ]
