# Generated by Django 4.2.6 on 2023-11-11 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices_analyzer', '0007_alter_petroleum_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petroleum',
            name='basis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='petroleums', to='prices_analyzer.basis'),
        ),
        migrations.AlterField(
            model_name='petroleum',
            name='product_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='petroleums', to='prices_analyzer.productkey'),
        ),
    ]
