# Generated by Django 4.2.6 on 2023-11-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rail_tariff', '0006_alter_railtariff_rail_code_base_from_and_more'),
        ('prices_analyzer', '0008_alter_petroleum_basis_alter_petroleum_product_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='rzd_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rail_tariff.rzdcode'),
        ),
        migrations.AlterField(
            model_name='productionplace',
            name='rzd_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rail_tariff.rzdcode'),
        ),
    ]
