# Generated by Django 4.2.7 on 2023-12-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices_analyzer', '0009_alter_depot_rzd_code_alter_productionplace_rzd_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prices',
            old_name='price',
            new_name='full_price',
        ),
    ]
