# Generated by Django 4.2.9 on 2024-01-30 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prices_analyzer', '0013_remove_depot_user_depot_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depot',
            name='user',
        ),
        migrations.AddField(
            model_name='depot',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
