# Generated by Django 4.2.9 on 2024-01-31 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices_analyzer', '0014_remove_depot_user_depot_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproductionplaces',
            old_name='production_place_id',
            new_name='production_place',
        ),
        migrations.RemoveField(
            model_name='userproductionplaces',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userproductionplaces',
            name='depot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='prices_analyzer.depot'),
            preserve_default=False,
        ),
    ]
