# Generated by Django 4.2.9 on 2024-01-31 13:13

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prices_analyzer', '0015_rename_production_place_id_userproductionplaces_production_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductionPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prices_analyzer.depot')),
                ('production_place', models.ManyToManyField(to='prices_analyzer.productionplace')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UserProductionPlaces',
        ),
    ]
