# Generated by Django 4.2.9 on 2024-02-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices_analyzer', '0016_userproductionplace_delete_userproductionplaces'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProductionPlace',
            new_name='UserRouts',
        ),
        migrations.AlterModelOptions(
            name='prices',
            options={'ordering': ['-full_price']},
        ),
    ]
