# Generated by Django 4.2.9 on 2024-02-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices_analyzer', '0017_rename_userproductionplace_userrouts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prices',
            options={'ordering': ['full_price']},
        ),
    ]
