# Generated by Django 4.2.9 on 2024-03-02 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices_analyzer', '0018_alter_prices_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrouts',
            name='production_place',
        ),
        migrations.AddField(
            model_name='userrouts',
            name='production_place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='prices_analyzer.productionplace'),
            preserve_default=False,
        ),
    ]
