# Generated by Django 4.2.9 on 2024-03-04 17:19

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rail_tariff', '0010_alter_rzdstation_code'),
        ('prices_analyzer', '0019_remove_userrouts_production_place_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrouts',
            options={'get_latest_by': 'created', 'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='FullPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('full_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('petroleum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='full_prices', to='prices_analyzer.petroleum')),
                ('rail_tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='full_prices', to='rail_tariff.railtariff')),
                ('user_routs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='full_prices', to='prices_analyzer.userrouts')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
