# Generated by Django 4.2.6 on 2023-11-01 11:45

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RailTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name_base_to', models.CharField(max_length=1000)),
                ('rail_code_base_to', models.SmallIntegerField()),
                ('name_base_from', models.CharField(max_length=1000)),
                ('code_base_from', models.CharField(max_length=3)),
                ('rail_code_base_from', models.SmallIntegerField()),
                ('cargo', models.CharField(choices=[('AB', 'Ab'), ('DT', 'Dt'), ('OTHER', 'Other')], max_length=5)),
                ('distance', models.SmallIntegerField()),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
