# Generated by Django 4.2.6 on 2023-11-09 09:10

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prices_analyzer', '0004_basis_productkey_sort_alter_petroleum_options_and_more'),
        ('rail_tariff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='railtariff',
            name='code_base_from',
        ),
        migrations.RemoveField(
            model_name='railtariff',
            name='name_base_from',
        ),
        migrations.RemoveField(
            model_name='railtariff',
            name='name_base_to',
        ),
        migrations.AddField(
            model_name='railtariff',
            name='weight',
            field=models.SmallIntegerField(choices=[(52, 'AB'), (55, 'DT')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='railtariff',
            name='cargo',
            field=models.SmallIntegerField(choices=[(21105, 'AB'), (21404, 'DT')]),
        ),
        migrations.CreateModel(
            name='ProductionPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rzd_code', models.SmallIntegerField()),
                ('production_place_name', models.CharField(max_length=1000)),
                ('basis', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='production_places', to='prices_analyzer.basis')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('depot_name', models.CharField(max_length=1000)),
                ('production_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='rail_tariff.productionplace')),
                ('rail_tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='rail_tariff.railtariff')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
