# Generated by Django 4.2.6 on 2023-11-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rail_tariff', '0002_remove_railtariff_code_base_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionplace',
            name='basis',
        ),
        migrations.DeleteModel(
            name='Depot',
        ),
        migrations.DeleteModel(
            name='ProductionPlace',
        ),
    ]
