# Generated by Django 4.2.6 on 2023-11-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rail_tariff', '0004_rzdcode_alter_railtariff_rail_code_base_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railtariff',
            name='rail_code_base_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rail_code_base_from', to='rail_tariff.rzdcode'),
        ),
        migrations.AlterField(
            model_name='railtariff',
            name='rail_code_base_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rail_code_base_to', to='rail_tariff.rzdcode'),
        ),
    ]
