# Generated by Django 4.2.7 on 2023-11-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail_tariff', '0006_alter_railtariff_rail_code_base_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rzdcode',
            name='code',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
