# Generated by Django 4.2.8 on 2023-12-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail_tariff', '0007_alter_rzdcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railtariff',
            name='distance',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='rzdcode',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
