# Generated by Django 4.2.9 on 2024-02-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail_tariff', '0009_rename_rzdcode_rzdstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rzdstation',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
