name: CI

on:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.7
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
      - name: Install dependencies
        run: pdm install
      - name: Run ruff
        run: ruff .
      - name: Run mypy
        run: mypy .
      - name: Run tests
        run: pytest --cov --lf -vv .
