name: Deploy

on:
  push:
    tags: [ '*.*.*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOYUSER_SSH_PRIVATE_KEY }}

      - name: Disable Host key verification
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Copy docker-compose.yaml with tags
        run: scp ./deploy/docker-compose.yaml deployuser@petroleum-prices.ru:./
        
      - name: Pull image
        env:
          VERSION: ${{ steps.meta.outputs.tags }}
        run: ssh deployuser@petroleum-prices.ru "VERSION=${VERSION} docker compose pull"
        
      - name: Stop services
        run: ssh deployuser@petroleum-prices.ru "VERSION=$tags docker compose stop web worker nginx"
        
      - name: Run servises
        run: ssh deployuser@petroleum-prices.ru "VERSION=$tags docker compose up -d web worker"

