name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOYUSER_SSH_PRIVATE_KEY }}

      - name: Disable Host key verification
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Copy docker-compose.yaml with tags
        run: scp ssh "deployuser@petroleum-prices.ru:./deploy/docker-compose.yaml ~/"
        
      - name: Pull image
        run: ssh deployuser@petroleum-prices.ru "docker compose pull"
        
      - name: Stop services
        run: ssh deployuser@petroleum-prices.ru "docker compose stop web worker"
        
      - name: Run servises
        run: ssh deployuser@petroleum-prices.ru "docker compose up -d web worker" 

