name: Deploy

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOYUSER_SSH_PRIVATE_KEY }}

      - name: Disable Host key verification
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Copy docker-compose.yaml with tags
        run: scp ./deploy/docker-compose.yaml deployuser@petroleum-prices.ru:./
        
      - name: Pull image
        run: ssh deployuser@petroleum-prices.ru "docker compose pull"
        
      - name: Stop services
        run: ssh deployuser@petroleum-prices.ru "docker compose stop web worker nginx"
        
      - name: Run servises
        run: ssh deployuser@petroleum-prices.ru "docker compose up -d web worker nginx" 

